fix lib
ffc-nectec/api pull request #58
Opened 2021-12-13 16:17 UTC by lionants02

รอทดสอบก่อน ค่อยเอาเข้า master

2021-12-24 12:38 UTC, piruin requested changes

2021-12-24 12:38 UTC, piruin commented on build.gradle
> +    //maven { url "https://dl.bintray.com/blazei/maven" }  // ไม่มีไฟล์
ลบออกไปเลยครับ ของ bintray เค้าไปปิดแล้ว

2021-12-24 12:38 UTC, piruin commented on build.gradle
> +    //compile 'com.github.piruin:jbcrypt:0.4' // ไม่มีไฟล์
นี้ด้วย

2023-01-12 05:21 UTC, lionants02 commented on build.gradle
> +    //maven { url "https://dl.bintray.com/blazei/maven" }  // ไม่มีไฟล์
ปรับแก้แล้วครับ

2026-07-05 14:16 UTC, closed without merging